api_platform:
    title: Event Management API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        attributes:
            normalization_context: { groups: [ 'read' ] }
            denormalization_context: { groups: [ 'write' ] }
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_enabled: true
        pagination_items_per_page: 10
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header
    enable_swagger: true
    enable_swagger_ui: true
    enable_re_doc: true
    show_webby: false
