vich_uploader:
    db_driver: orm # Database driver (e.g., orm, mongodb)
    mappings:
        event_media: # A unique identifier for this mapping
            uri_prefix: /uploads/event_media # Public URL prefix
            upload_destination: '%kernel.project_dir%/public/uploads/event_media' # Directory where files are stored
            namer:
                service: Vich\UploaderBundle\Naming\UniqidNamer # Automatically generate unique names
            delete_on_remove: true # Delete files when the entity is removed
            delete_on_update: true # Delete old files when a new one is uploaded
            inject_on_load: false # Prevent file injection during entity hydration
